### ISSUE TITLE
openssl-3.2 test breakage

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts-hardened#138]
One of our tests is broken when using an image with openssl 3.2 in it. Some details in:
https://github.com/spiffe/helm-charts-hardened/pull/134

**Comment by drewwells** [comment]
does the script have write permissions to /tmp folder? The tmp files are all empty

hmm, the tmp files are empty. Maybe write permission silently failing or something else is up
```
-rw-------    1 1000     1000           0 Dec  8 16:55 tmp.8krdaf
-rw-------    1 1000     1000           0 Dec  8 16:55 tmp.Ag62jD
-rw-------    1 1000     1000           0 Dec  8 17:07 tmp.IO6ByS
-rw-------    1 1000     1000           0 Dec  8 17:07 tmp.aendPB
-rw-------    1 1000     1000           0 Dec  8 17:07 tmp.pzNBhB
-rw-------    1 1000     1000           0 Dec  8 16:55 tmp.qiPnZQ
```

**Comment by drewwells** [comment]
Well I thought it was working, but I'm still having issues with it as seen in the CI. I filed a bug upstream with openssl because 3.2.0 has a lot of issues when I use asn1parse.

https://github.com/openssl/openssl/issues/22992

**Comment by drewwells** [comment]
Well upstream has been fixed. I did not succeed in building and installing openssl to an alternate location to validate if it fixes this issue. I'd like to get simpler logic to verify the JWTs, but it took me a significant amount of time to find this approach. Maybe I can talk somebody over at https://smallstep.com/docs/step-cli/ to implement public key validation.

**Comment by kfox1111** [comment]
Cool. So, the day after they release there should be a chainguard image with the fixes.

**Comment by drewwells** [comment]
I've figured out how to do it with the `step` cli tool and much simpler logic. I'm verifying how I can use step with this process
