### ISSUE TITLE
Update HorizontalPodAutoscaler API to autoscaling/v2

### ISSUE THREAD

**Issue by jer8me** [spiffe/helm-charts-hardened#140]
autoscaling/v2beta1 was removed in Kubernetes 1.25: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25 and autoscaling/v2 is available since Kubernetes 1.23.
We should change the SPIRE server and OIDC Discovery Provider charts to use autoscaling/v2 for the HPA.

I am more than happy to open a PR for this!

**Comment by kfox1111** [comment]
Sounds great. Happy to have a PR for this. Thanks! :)

**Comment by jer8me** [comment]
Thanks kfox1111. It looks like only Collaborators can open PRs. Any way to be added?

**Comment by kfox1111** [comment]
Hmm.. should be able to...

Try:
hitting the 'fork'  button at the top of https://github.com/spiffe/helm-charts-hardened, select your username as the org, then push the changes to a branch at that location. Once committed to your copy of the repo, it should allow a pr to be created against this repo.

**Comment by jer8me** [comment]
Yeah, the issue was on my end, PR is open now. Thank you!
