### ISSUE TITLE
HA Spire

### ISSUE THREAD

**Issue by drewwells** [spiffe/helm-charts-hardened#209]
Now that on-disk caching has been migrated, we should be unblocked on using HA for the spire server. What's blocking us from removing the statefulset and using a deployment? Even a single replica would be a helpful improvement if replica >1 still requires more work ie. leader election.

https://github.com/spiffe/helm-charts-hardened/blob/main/charts/spire/charts/spire-server/templates/statefulset.yaml

**Comment by faisal-memon** [comment]
With 1.9.0 SPIRE release we should now be able to do this if SPIRE is configured with Postgres or Mysql database.

**Comment by drewwells** [comment]
Highly recommend database in a pod. We use bitnami/postgresql for this. If it's desirable that helm-charts-hardened is easily used as a subchart, then I would not recommend subcharting postgresql but instead diy database in a pod.

**Comment by kfox1111** [comment]
1.9 was just released so this is unblocked

**Comment by anhpatel** [comment]
@faisal-memon  Can you assign this issue to me? 
Are there any pointers/gotchas that I should be thinking about? I was thinking if datastore configuration for mysql/postgres is defined, we use deployment for spire-server.

**Comment by anhpatel** [comment]
So a flag called 'stateless'(?) and that being true along with mysql and postgres configuration can render a deployment. Just wondering if that introduces failure due to misconfiguration cases and if that matters.

**Comment by faisal-memon** [comment]
Thanks @anhpatel for volunteering to work on this.

**Comment by faisal-memon** [comment]
> I'm thinking there may be reasons for users to still use persistence even when using mysql/postgresql (?), so maybe we don't autoset which mode is used but make an option to select which one to use, and then fail if configured in an incomparable way?

@kfox1111  I was thinking to autoset it too. Perhaps we can have auto as the default and then a way to force a mode if the user wants to?

**Comment by kfox1111** [comment]
Was thinking to keep things simple by not supporting autoset out of the box initially, but do that in a follow on pr.

But, I guess either way (having fail messages if incompatable options, or autodetecting the right mode) we might need to survey the available settings that could require persistence and note their incompatibilities. So maybe the bulk of the work is the same either way?

I do think autoset could be very useful. Just unclear what logic it would need to make it a thing. Do we want to figure that out before hand or land a Deployment supporting PR and then figure out how to make autoset a thing before 1.0? If we can't do a PR without doing the bulk of the work for a fail message, then we might as well go straight to supporting autoset?

**Comment by anhpatel** [comment]
In that case, I think as an initial PR, if external datastore is configured along with 'stateless' set to true can land a deployment and keep it as is for default. That way we ensure backward compatibility and start by using deployments only if explicitly asked for.

**Comment by kfox1111** [comment]
I think the devil is in the details of all the values we have.

We have some like `spire-server.persistence.type` that could be used to indicate you don't want persistence. Though emptyDir is currently marked testing only, and intended for use when you want to pretend you have persistence but dont actually want it, which is different then explicitly not wanting persistence and don't want to accidentally loose data. We don't currently have any other way for the user to say they don't desire persistence. We may need a new flag.

Other values such as `spire-server.dataStore.sql.databaseType` that may or may not require persistence depending on what its set to.

Some other plugins that need persistence enabled to function, such as `spire-server.keyManager.disk` or `spire-server.tornjak`. 

There may be some configurations of `spire-server.unsupportedBuiltInPlugins` that need persistence... we could possibly just throw a warning and ignore it as its unsupported.

`spire-server.customPlugins`: is harder, as some plugins may assume persistence and we really don't have any way to predict it. We could maybe assume persistence is required if set, or have some setting that says the user has vetted it.

Not an exhaustive list, just ones I found at a quick skim.

I could see maybe an explicit:
`deploymentType` flag or something that initially supports oneOf [statefulset (default), deployment]  with the future possibilities of adding [none, auto, daemonset] as well.

**Comment by drewwells** [comment]
The real goal here is to move spire server over to a stateless microservice, so multiple pods can be run to ensure high availability and survive AZ outages. I wouldn't get distracted with needs of possible custom plugins, as those plugin developers can solve this problem on their own. 

I strongly advocate deployment becomes the only option for running spire-server. I see a lot of complicated configurations to sort of pseudo support stateful or stateless setups. We should make a decision now which way it will run. If spire-server is going to be stateful, then I'll have to move our architecture off of it. We can't have an authentication system that can go down b/c one pod's dies or loses state.

**Comment by anhpatel** [comment]
We can start with a top-level flag `deploymentType` that you can set if you want to use deployment and by doing that user assumes responsibility of having vetted all configurations. We can individually look into fixing incompatible plugins in follow up PRs as required. This way we don't break any current configurations and start making progress on migrating to deployment.

**Comment by drewwells** [comment]
I can't get previous logs for a statefulset, so I can't debug this intermittent crashing of spire-server. I'm looking forward to #293 being merged and available as a release.
```
❯ k -n spire-server logs -p spire-server-0                                                                                  ⛵ box-4
Error from server (BadRequest): previous terminated container "spire-server" in pod "spire-server-0" not found

❯ k -n spire-server get po spire-server-0            
NAME             READY   STATUS    RESTARTS        AGE
spire-server-0   2/2     Running   7 (6m31s ago)   28m
```

**Comment by kfox1111** [comment]
PR #293 wouldn't help with skip upgrading from chart version 0.11.0 right to 0.19.0. There is still a persistent database that wouldn't have gotten the spire schema updates so likely would see the same issue.
