### ISSUE TITLE
what to do with examples/production

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts-hardened#217]
examples/production/ is not as useful as it was in the past. The vast majority of things it did are now in the chart now via recommendations. The documentation facet of it is better handled via chart/README.md and the spiffe.io website. And the test functionality is a little counter to it being a good example.

So, we should figure out what to do with it.

Currently thinking of moving it to tests/integration/production

**Comment by marcofranssen** [comment]
Some things to handle when moving:

- [ ] Update workflow regarding examples test
- [ ] Update branch protections to require another mandatory job (remove examples/production with new job)
