### ISSUE TITLE
Ensure that the agent admin socket can be enabled

### ISSUE THREAD

**Issue by edwbuck** [spiffe/helm-charts-hardened#224]
The Agent configuration supports an agent level setting agent_admin_socket which describes the Unix Domain Socket for Agent administration APIs.

Recent work on configurable log levels will place the post-log level adjustment commands on this socket.  It would be nice to have this setting be supported.

Support includes:

- having a pod-private volume to hold the socket
- ensuring that this volume is mounted in a directory higher than the workload API Unix Domain Socket (to satisfy the configuration file sanity checks in SPIRE)
- ensuring that the pod-private socket is exposed to the pod that holds the spire-agent executable, so the agent executable can be used as a client of the socket to adjust the already-running agent process.

**Comment by kfox1111** [comment]
Does the spire-agent executable look for the admin socket in any particular place by default or does it look at the default config file and read it from there?

**Comment by kfox1111** [comment]
Somewhat related to https://github.com/spiffe/helm-charts-hardened/issues/177 as well.

**Comment by kfox1111** [comment]
Looking around, cilium is using the admin socket from their own pod for the delegated identity api. So we also need the ability to hostPath export it.

**Comment by kfox1111** [comment]
https://github.com/spiffe/spire/pull/4856

**Comment by kfox1111** [comment]
pr 4856 merged, so the default will be:
"/tmp/spire-agent/private/admin.sock"
