### ISSUE TITLE
Allow audit_log_enabled to be configurable via values

### ISSUE THREAD

**Issue by mcrors** [spiffe/helm-charts-hardened#239]
I'd like to be able to switch audit_log_enabled via a configMap. I know that this is possible via environment variable as well. I was wondering if there's a reason why it's not available to do with the config map?

**Comment by kfox1111** [comment]
No reason other then just not getting implemented yet. Will prioritize this.

**Comment by mcrors** [comment]
No need. I can make the update and create a PR by the end of the week. Thanks for the feedback.

**Comment by faisal-memon** [comment]
@mcrors That would great.
