### ISSUE TITLE
Drop spire version ranges

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts-hardened#25]
Here: https://github.com/spiffe/helm-charts-hardened#dependencies-and-version-compatibility

we claim to support all the 1.6.x and 1.7.x series. We don't test hardly any of it though. Thinking we should only claim official support of the version we are testing/releasing a particular version of the chart with?

**Comment by faisal-memon** [comment]
That table is definitely out of date.  That sounds fine to me.
