### ISSUE TITLE
SPIRE 1.9 support

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts-hardened#261]
These need to happen before 1.9 support in the chart is released:
* https://github.com/spiffe/spire/pull/4791 has a flag and an upgrade note to add to the chart.
* - `uniqueid` CredentialComposer plugin that adds the x509UniqueIdentifier attribute to workload X509-SVIDs (#4862) needs to be added and an upgrade note about it added.

Also https://github.com/spiffe/helm-charts-hardened/issues/209 is unblocked but shouldn't block a 1.9 based release.

**Comment by faisal-memon** [comment]
Yes we can do the run spire as a deployment part as a follow on pr.
