### ISSUE TITLE
spiffe-oidc-discovery-provider - Allow disabling csi driver and specifying custom volume 

### ISSUE THREAD

**Issue by PeterSR** [spiffe/helm-charts-hardened#367]
Due to https://github.com/spiffe/spiffe-csi/issues/196 I am not able to use the CSI driver. Is there a way to use the helm chart for the `spiffe-oidc-discovery-provider` without the CSI driver? Perhaps a way to manually control the `spiffe-workload-api` volume.

**Comment by kfox1111** [comment]
The csi driver is critical to the proper functioning of spire on kubernetes. We should be able to get the driver to function rather then disable it and then have a pretty unusable spire. Closing in favor of fixing the issues in #196.

**Comment by kfox1111** [comment]
Thanks for filing the issue though. I did not see the issue until it was filed here. I don't have a watch on the spiffe-csi repo.
