### ISSUE TITLE
Chart project status and relationship to helm-charts-flex?

### ISSUE THREAD

**Issue by kamalmarhubi** [spiffe/helm-charts-hardened#425]
Hello! The former [helm charts repo][old] refers to both this repo and the [helm-charts-flex] repo as successors. I'm trying to understand the development status and relationship between the two, especially as this repo seems to have much more recent activity than the other.

I opened an equivalent issue on the other repo: https://github.com/spiffe/helm-charts-flex/issues/28

[old]: https://github.com/spiffe/helm-charts
[helm-charts-hardened]: https://github.com/spiffe/helm-charts-flex

**Comment by kfox1111** [comment]
The charts in this repo are actively developed and used currently in production by multiple organizations. The flex project can weigh in on https://github.com/spiffe/helm-charts-flex/issues/28. The rest, is too long a story for a github issue.

**Comment by kamalmarhubi** [comment]
Thanks for the quick reply!
