### ISSUE TITLE
Unable to set dbtype/connection_string via plugin_data

### ISSUE THREAD

**Issue by arvindth** [spiffe/helm-charts-hardened#441]
It's not clear if this is an overlooked bug or a desired feature, but it looks like neither the `database_type` nor the `connection_string` can be set via `.Values.dataStore.sql.plugin_data`, even though [this line in values.yaml](https://github.com/spiffe/helm-charts-hardened/blob/532852d9072e50be976ad7cd6dedb0f8bafe3e4c/charts/spire/charts/spire-server/values.yaml#L173-L174) seems to indicate it's possible.

[This section in _helpers.tpl](https://github.com/spiffe/helm-charts-hardened/blob/532852d9072e50be976ad7cd6dedb0f8bafe3e4c/charts/spire/charts/spire-server/templates/_helpers.tpl#L192-L208) overwrites both `database_type` and `connection_string` from plugin_data, and there doesn't seem to be a way to skip the overwrite.

Perhaps the section could be wrapped with a
```
{{- if .Values.dataStore.sql.databaseType }}
```
so that if we don't specify the `databaseType`, the values from `plugin_data` get used? But then it's not clear what the desired outcome should be if plugin_data doesn't contain the required `database_type` and `connection_string` values.

Or perhaps the plugin_data should get merged in afterwards, but then it's not clear what should happen if the values are specified in both places.

**Comment by kfox1111** [comment]
You can set connection string and database_type from:
https://github.com/spiffe/helm-charts-hardened/blob/532852d9072e50be976ad7cd6dedb0f8bafe3e4c/charts/spire/charts/spire-server/values.yaml#L159-L171

**Comment by arvindth** [comment]
Yes, that's exactly what I wound up doing. And I suppose that's my question - is it expected that we're not able to specify `connection_string` and `database_type` via plugin_data even though https://github.com/spiffe/spire/blob/main/doc/plugin_server_datastore_sql.md lists them as potential fields?

The reason I filed this issue is that I added it via plugin_data, and then scratched my head for a while wondering why it didn't apply until I went through _helpers.tpl and realized that it gets immediately overwritten.

What's even the point of supporting plugin_data then? Is it only for the other fields listed in https://github.com/spiffe/spire/blob/main/doc/plugin_server_datastore_sql.md?

**Comment by faisal-memon** [comment]
Yes. That makes sense.

**Comment by arvindth** [comment]
@kfox1111 @faisal-memon this answers my question. Let me know if you wanted to keep this issue open for any followup. Otherwise, I'll go ahead and close it in the next day or so.
