### ISSUE TITLE
 Feature: Add support for IAM auth via aws_postgres

### ISSUE THREAD

**Issue by arvindth** [spiffe/helm-charts-hardened#451]
We got support for `aws_postgres` dbtype in https://github.com/spiffe/spire/pull/4828. However, there's no current way to pass this via the helm chart. 

Could we either add direct support for `aws_postgres`, or allow `plugin_data`'s `dbtype` and `connection_string` to be respected until we do?

**Comment by kfox1111** [comment]
The devil in the details is going to be around how IAM auth works in k8s?

How does the spire-server pod get the credentials?

**Comment by kfox1111** [comment]
This depends on https://github.com/spiffe/spire/issues/5495

**Comment by kfox1111** [comment]
Can you please try https://github.com/spiffe/helm-charts-hardened/pull/464 in a test environment and see if it works for you? I don't have a way to test it.

**Comment by arvindth** [comment]
Hey @kfox1111, unfortunately it'll be a little while before I'm at the state where I can test this out. Once I'm able, I'll report back.

**Comment by arvindth** [comment]
Hi @faisal-memon, unfortunately, I won't have access to a good test environment for little while yet.

**Comment by kfox1111** [comment]
Ok, thanks. We will close the ticket for now, as we believe the chart has all the options needed. If you run into any issues with the support in the future, please either file a new ticket or reopen this one.
