### ISSUE TITLE
Better repo readme

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts-hardened#57]
It was brought up that going to github.com/spiffe/helm-charts-hardened that there is a lack of, how to install the chart.

**Comment by faisal-memon** [comment]
@kfox1111 can you list out what all needs to be done.

**Comment by kfox1111** [comment]
We need to figure out how we're going to recommend a production deployment. Right now the instructions are pointing to the main branch examples/production but that could have some different settings/recommendations then what is appropriate for any given released version of the chart.

And the examples just assumes you already have a git checkout of the right version, using the chart from the checkout rather then the remote repo.

We could have the chart's readme point at the particular release branch by version number, or to a website that renders out the documentation per version. The latter may be cleaner but is more work. cert-manager is an example where they version the site. Like, https://cert-manager.io/v1.9-docs

**Comment by kfox1111** [comment]
This is mostly complete. The remainders are in:
* https://github.com/spiffe/helm-charts-hardened/pull/114
* https://github.com/spiffe/spiffe.io/pull/290

**Comment by faisal-memon** [comment]
Closing as we've made enhancements. Any docs requests should be done through a specific issue request.
